title: Faroxy Documentation
description: Documentation for Faroxy - A modern HTTP proxy server
baseurl: "/faroxy"
url: "https://vinipx.github.io/faroxy"
repository: vinipx/faroxy

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

logo: "/assets/images/faroxy-logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Aux links for the upper right navigation
aux_links:
  "Faroxy on GitHub":
    - "https://github.com/vinipx/faroxy"

# Enable or disable the site search
search_enabled: true

# Set the search token separator
search:
  tokenizer_separator: /[\s/]+/

# Heading anchor links
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2025 Faroxy. Distributed under the MIT license."
